version: "3.7"

services:
  db:
    image: postgres:16
    container_name: db_app
    command: postgres -p 1221  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tiny_url
    ports:
      - "1221:1221"  #
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  redis:
    image: redis:7
    container_name: redis_app
    command: redis-server --port 5370
    ports:
      - "5370:5370"

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=1221
      - DB_NAME=tiny_url
      - CELERY_BROKER_URL=redis://redis:5370/0
      - CELERY_RESULT_BACKEND=redis://redis:5370/0

  celery:
    build:
      context: .
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:5370/0
      - CELERY_RESULT_BACKEND=redis://redis:5370/0

volumes:
  postgres_data: