version: "3.7"

services:
  db:
    image: postgres:16
    container_name: db_app
    command: postgres -p 1221  
    env_file:
      - .env
    ports:
      - "1221:1221"  #
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  redis:
    image: redis:7
    container_name: redis_app
    command: redis-server --port 5370
    ports:
      - "5370:5370"

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build:
      context: .
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data: