"""del user_id

Revision ID: ec447078b3b6
Revises: 5559a3ce962f
Create Date: 2025-03-23 13:54:07.902468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec447078b3b6'
down_revision: Union[str, None] = '5559a3ce962f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Убедимся, что столбец email в таблице user имеет уникальное ограничение
    op.create_unique_constraint("uq_user_email", "user", ["email"])

    # Добавляем новый столбец user_email в таблицу url
    op.add_column('url', sa.Column('user_email', sa.String(), nullable=True))

    # Удаляем старый внешний ключ user_id
    op.drop_constraint('url_user_id_fkey', 'url', type_='foreignkey')

    # Создаем новый внешний ключ, ссылающийся на email в таблице user
    op.create_foreign_key(
        "fk_url_user_email",  # Имя ограничения
        "url",               # Таблица, в которой создается внешний ключ
        "user",              # Таблица, на которую ссылается внешний ключ
        ["user_email"],      # Столбец в таблице url
        ["email"]            # Столбец в таблице user
    )

    # Удаляем старый столбец user_id
    op.drop_column('url', 'user_id')

    # Удаляем уникальное ограничение на username (если оно существует)
    op.drop_constraint('user_username_key', 'user', type_='unique')

    # Удаляем столбец username
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Восстанавливаем столбец username
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))

    # Восстанавливаем уникальное ограничение на username
    op.create_unique_constraint('user_username_key', 'user', ['username'])

    # Восстанавливаем столбец user_id в таблице url
    op.add_column('url', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # Удаляем внешний ключ, ссылающийся на email
    op.drop_constraint("fk_url_user_email", "url", type_='foreignkey')

    # Восстанавливаем старый внешний ключ, ссылающийся на id
    op.create_foreign_key(
        'url_user_id_fkey',  # Имя ограничения
        'url',              # Таблица, в которой создается внешний ключ
        'user',             # Таблица, на которую ссылается внешний ключ
        ['user_id'],        # Столбец в таблице url
        ['id']              # Столбец в таблице user
    )

    # Удаляем столбец user_email
    op.drop_column('url', 'user_email')

    # Удаляем уникальное ограничение на email
    op.drop_constraint("uq_user_email", "user", type_='unique')
    # ### end Alembic commands ###